baseurl = "/"
title = "Revenue Acceleration LLC"
theme = "universal"
languageCode = "en-us"
defaultContentLanguage = "en"
# disqusShortname = "revenueHealth"
# googleAnalytics = "" #TODO need to add GA code

# Define the number of posts per page
paginate = 50

[menu]

# Main menu

[[menu.main]]
    name = "Home"
    url  = "/"
    weight = 1

[[menu.main]]
    name = "Blog"
    url  = "/blog/"
    weight = 2

[[menu.main]]
    name = "FAQ"
    identifier = "faq"
    url  = "/faq/"
    weight = 3

[[menu.main]]
    name = "Contact"
    url  = "/contact/"
    weight = 4

# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "Facebook"
    url = "http://facebook.com"
    pre = "<i class='fa fa-2x fa-facebook'></i>"

[[menu.topbar]]
    weight = 2
    name = "Twitter"
    url = "https://twitter.com/RevenueAccel"
    pre = "<i class='fa fa-2x fa-twitter'></i>"

[[menu.topbar]]
    weight = 3
    name = "LinkedIn"
    url = "https://www.linkedin.com/company/revensuehealth/"
    pre = "<i class='fa fa-2x fa-linkedin'></i>"

[[menu.topbar]]
    weight = 4
    name = "Email"
    url = "mailto:info@revenue.health"
    pre = "<i class='fa fa-2x fa-envelope'></i>"

[params]
    viewMorePostLink = "/blog/"
    author = "Revenue Accelerators"
    defaultKeywords = ["revenue"]
    defaultDescription = "Our expert opinions"

    # Google Maps API key (if not set will default to not passing a key.)
    googleMapsApiKey = ""

    # Enable the contact form by entering your Formspree.io email
    email = "shahid.shah@netspective.com"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "violet"

    about_us = "<p>Revenue Health is a complete Healthcare Solutions company specializing in revenue cycle management.</p>"
    copyright = "Copyright (C) 2018 Revenue Acceleration LLC. All Rights Reserved."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    logo = "img/logo.jpg"
    address = """<p><strong>Revenue Acceleration LLC</strong>
        <br>Silver Spring, MD USA
      </p>
      """
    latitude = "38.897663300"
    longitude = "-77.036573900"

[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = true
    text = """<p class="hidden-sm hidden-xs">Contact us on 301-478-0590 or <a href="mailto:info@revenue.health?subject=Help%20accelerate%20my%20revenue">info@revenue.health</a>.</p>
      <p class="hidden-md hidden-lg"><a href="#" data-animate-hover="pulse"><i class="fa fa-phone"></i></a>
      <a href="#" data-animate-hover="pulse"><i class="fa fa-envelope"></i></a>
      </p>
      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carousel]
    enable = true
    # All carousel items are defined in their own files. You can find example items
    # at 'data/carousel'.
    # For more informtion take a look at the README.

[params.features]
    enable = true
    # All features are defined in their own files. You can find example items
    # at 'data/features'.
    # For more informtion take a look at the README.

[params.testimonials]
    enable = true
    # All testimonials are defined in their own files. You can find example items
    # at 'data/testimonials'.
    # For more informtion take a look at the README.
    title = "Testimonials"
    subtitle = "We have worked with many clients and we always like to hear they come out from the cooperation happy and satisfied. Have a look what our clients said about us."

[params.see_more]
    enable = true
    icon = "fa fa-file-code-o"
    title = "Ready to have us start doing your billing?"
    subtitle = "Give us a call, have us call you, or drop us a message to get more information."
    link_url = "contact"
    link_text = "Contact Us"

[params.clients]
    enable = true
    # All clients are defined in their own files. You can find example items
    # at 'data/clients'.
    # For more informtion take a look at the README.
    title = "Our Clients"
    subtitle = ""

[params.recent_posts]
    enable = true
    title = "Learn from our Experts"
    subtitle = "We know what we're doing. But don't just take our word for it, visit our blog often to see how we solve problems for our customers."
