baseurl = "https://www.revenue.health/"
title = "Healthcare Revenue Cycle Management & Administration | Revenue Acceleration LLC"
theme = "universal"
languageCode = "en-us"
defaultContentLanguage = "en"
# disqusShortname = "revenueHealth"
# googleAnalytics = "" #TODO need to add GA code

# Define the number of posts per page
paginate = 10

[menu]

# Main menu

[[menu.main]]
    name = "Home"
    url  = "/"
    weight = 1

[[menu.main]]
    name = "Home Health"
    url  = "/home-health/"
    weight = 2

[[menu.main]]
    name = "PDGM"
    url  = "/pdgm/"
    weight = 3

[[menu.main]]
    name = "Blog"
    url  = "/blog/"
    weight = 4

[[menu.main]]
    name = "News"
    url  = "/news/"
    weight = 5

[[menu.main]]
    name = "FAQ"
    identifier = "faq"
    url  = "/faq/"
    weight = 6

[[menu.main]]
    name = "Team"
    url  = "/executive-team/"
    weight = 7

#[[menu.main]]
#   name = "Advisory Board"
#   url  = "/advisory-board/"
#    weight = 8	
	
[[menu.main]]
    name = "Contact"
    url  = "/contact/"
    weight = 9

	
[footermenu]
# Footer menu
[[menu.footermenu]]
    name = "Home"
    url  = "/"
    weight = 1
[[menu.footermenu]]
    name = "PDGM"
    url  = "/pdgm/"
    weight = 2
[[menu.footermenu]]
    name = "Blog"
    url  = "/blog/"
    weight = 3

[[menu.footermenu]]
    name = "News"
    url  = "/news/"
    weight = 4

[[menu.footermenu]]
    name = "FAQ"
    identifier = "faq"
    url  = "/faq/"
    weight = 5

[[menu.footermenu]]
    name = "Team"
    url  = "/executive-team/"
    weight = 6

[[menu.footermenu]]
    name = "Contact"
    url  = "/contact/"
    weight = 7
[[menu.footermenu]]
    name = "Sitemap"
    url  = "/sitemap/"
    weight = 8

# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "Twitter"
    url = "https://twitter.com/RevenueAccel"
    pre = "<i class='fa fa-2x fa-twitter'></i>"

[[menu.topbar]]
    weight = 2
    name = "LinkedIn"
    url = "https://www.linkedin.com/company/revensuehealth/"
    pre = "<i class='fa fa-2x fa-linkedin'></i>"

[[menu.topbar]]
    weight = 3
    name = "Email"
    url = "mailto:info@revenue.health"
    pre = "<i class='fa fa-2x fa-envelope'></i>"

[params]
    viewMorePostLink = "/blog/"
    author = "Revenue Accelerators"
    metatitle ="Healthcare Revenue Cycle Management & Administration | Revenue Acceleration LLC"
    defaultKeywords = ["revenue"]
    defaultDescription = "Our Executive Team brings together decades of experience in Revenue Cycle Management & Healthcare Administration - to provide you with the best way to get paid!"
    NewsTitle ="Healthcare IT Administration News | Data Security Updates| Revenue Acceleration LLC "
    NewsDescription ="Find  new technologies in healthcare management with Revenue Acceleration. Get updated with news on patient driven groupings model and revenue cycle management."
    BlogTitle ="Revenue Cycle Management & Compliance Blogs | Revenue Acceleration LLC "
    BlogDescription ="Revenue acceleration functions with  revenue cycle management (RCM) and  compliance strategy for enhancing revenue for a hospital."
    ogimage ="/img/default-banner.jpg"
    elasticSearchUrl = "https://prod-es.medigy.com/"


    # Google Maps API key (if not set will default to not passing a key.)
    googleMapsApiKey = ""

    # Enable the contact form by entering your Formspree.io email
    email = "info@revenue.health"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "violet"

    about_us = "<p>Revenue Health is a complete Healthcare Solutions company specializing in revenue cycle management.</p>"
    copyright = "Copyright (C) 2020 <a href='https://www.revenue.health/'>Revenue Acceleration LLC</a> - Healthcare Revenue Cycle Management & Administration. All Rights Reserved."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    logo = "img/logo.png"
    logoalt ="Healthcare Revenue Cycle Management & Administration - Revenue Acceleration"
    address = """<p><strong itemprop="name">Revenue Acceleration LLC</strong>
        <br><span itemprop="address">Silver Spring, MD USA</span>
      </p>
      """
    latitude = "38.897663300"
    longitude = "-77.036573900"

[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = true
    text = """<p class="hidden-sm hidden-xs"><span itemprop="telephone">Contact us on 301-478-0590 </span>  or <a href="mailto:info@revenue.health?subject=Help%20accelerate%20my%20revenue" id="topbarcontactinfo" itemprop="email">info@revenue.health</a></p>
      <p class="hidden-md hidden-lg"><a href="#" data-animate-hover="pulse"><i class="fa fa-phone"></i></a>
      <a href="#" data-animate-hover="pulse"><i class="fa fa-envelope"></i></a>
      </p>
      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carousel]
    enable = true
    h1title ="Healthcare Revenue Cycle Management & Administration"
    # All carousel items are defined in their own files. You can find example items
    # at 'data/carousel'.
    # For more informtion take a look at the README.

[params.features]
    enable = true
    # All features are defined in their own files. You can find example items
    # at 'data/features'.
    # For more informtion take a look at the README.

[params.testimonials]
    enable = true
    # All testimonials are defined in their own files. You can find example items
    # at 'data/testimonials'.
    # For more informtion take a look at the README.
    title = "Testimonials"
    subtitle = "We have worked with many clients and we always like to hear they come out from the cooperation happy and satisfied. Have a look what our clients said about us."

[params.see_more]
    enable = true
    icon = "fa fa-file-code-o"
    title = "Ready to have us start doing your billing?"
    subtitle = "Give us a call, have us call you, or drop us a message to get more information."
    link_url = "contact"
    link_text = "Contact Us"

[params.clients]
    enable = true
    # All clients are defined in their own files. You can find example items
    # at 'data/clients'.
    # For more informtion take a look at the README.
    title = "Our Clients"
    subtitle = ""

[params.recent_posts]
    enable = true
    title = "Learn from our Experts"
    subtitle = "We know what we're doing. But don't just take our word for it, visit our blog often to see how we solve problems for our customers."
[taxonomies]
    news_sources = "news/source"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[module.imports]]
path                   = "gl.infra.medigy.com/medigy-presentation-content/news/revenue-health-curations.git"


[[module.imports.mounts]]
source                            = "content-auto"
target                            = "content"

[[module.imports.mounts]]
source                            = "content"
target                            = "content"

[[module.imports.mounts]]
source                            = "layouts"
target                            = "layouts"

[[module.imports.mounts]]
source                            = "static"
target                            = "static"

[[module.imports.mounts]]
source                            = "data"
target                            = "data"

