[build]
publish = "public"
command = "node create_md_files/createMdFile.js && hugo"

[context.production.environment]
HUGO_VERSION = "0.40.3"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.40.3"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.40.3"

[context.branch-deploy]
command = "hugo -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.40.3"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

  [[redirects]]
  from = "/our-approachpgdm"
  to = "/pgdm/"
  status = 301
  force = false
  
  [[redirects]]
  from = "/pgdm"
  to = "/pdgm/"
  status = 301
  force = false
  
  [[redirects]] 
  from = "/team"
  to = "/executive-team"
  status = 301
  force = false
