name: Run webhook

on:  
  schedule:
    - cron: '0 * * * *'  # every hour

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Execute webhook for netlify deployment
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/6013ea96b69cdce776148a40
